name: deploy
on:
  push:
    branches:
      - '*'
      - '!renovate/*'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/zeit-now@master
        env:
          ZEIT_TOKEN: ${{ secrets.ZEIT_TOKEN }}
  alias:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/zeit-now@master
        env:
          ZEIT_TOKEN: ${{ secrets.ZEIT_TOKEN }}
        with:
          args: alias
