name: deploy
on:
  push:
    branches:
      - '*'
      - '!renovate/*'
      - '!release'
jobs:
  lint-and-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: lint
        uses: stefanoeb/eslint-action@master
        with:
          args: . --ext .ts,.tsx
      - name: build-storybook
        uses: nuxt/actions-yarn@master
        with:
          args: run build-storybook
      - name: build-lib
        uses: nuxt/actions-yarn@master
        with:
          args: run build-lib
  deploy:
    needs: lint-and-build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/zeit-now@master
        env:
          ZEIT_TOKEN: ${{ secrets.ZEIT_TOKEN }}
