on: push
name: build and test
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: lint
      uses: stefanoeb/eslint-action@master
      with:
        args: . --ext .ts,.tsx
    - name: build
      uses: nuxt/actions-yarn@master
      with:
        args: run build-storybook
    - name: install
      uses: nuxt/actions-yarn@master
      with:
        args: install
