on: push
name: lint, build and publish
jobs:
  lint-build-and-publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: lint
      uses: stefanoeb/eslint-action@master
      with:
        args: . --ext .ts,.tsx
    - name: build-storybook
      uses: nuxt/actions-yarn@master
      with:
        args: run build-storybook
    - name: build-lib
      uses: nuxt/actions-yarn@master
      with:
        args: run build-lib
    - name: Publish Filter
      uses: actions/bin/filter@master
      with:
        args: branch master
    - name: Publish
      uses: mikeal/merge-release@master
      env:
        NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
